# Generated by Django 5.0.4 on 2024-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_special_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('b', 'برگشت داده شده'), ('p', 'منتتشر شده'), ('i', 'در حال بررسی'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
