# Generated by Django 5.0.4 on 2024-08-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('i', 'در حال بررسی'), ('b', 'برگشت داده شده'), ('d', 'پیش نویس'), ('p', 'منتتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
